sudo apt install openssh-server    
sudo apt install openvswitch-common
sudo apt install openvswitch-switch
sudo apt install php-common        
sudo apt install bpfcc-tools       
sudo apt install burp              
sudo apt install cryptmount        
sudo apt install dolphin-emu       
sudo apt install mailutils-mh      
sudo apt install mmh               
sudo apt install nmh  
