# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='four',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
